"""Pipeline router — start, status, SSE stream, ZIP download."""
import asyncio
import io
import json
import uuid
import zipfile
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from models.pipeline import Pipeline, PipelineStatus
from services import sse as sse_service
from services.orchestrator import start_pipeline, PIPELINE_MEMORY
from database import get_db

router = APIRouter(prefix="/api/pipeline", tags=["pipeline"])


class StartPipelineRequest(BaseModel):
    ideaText: str = Field(..., min_length=20, max_length=2000)
    userId: Optional[str] = "anonymous"
    tier: Optional[str] = "free"


class StartPipelineResponse(BaseModel):
    pipelineId: str
    status: str
    message: str


@router.post("/start", response_model=StartPipelineResponse)
async def start(body: StartPipelineRequest, db: AsyncSession = Depends(get_db)):
    """Create a pipeline record and launch background agent execution."""
    pipeline_id = str(uuid.uuid4())
    pipeline = Pipeline(
        id=pipeline_id,
        user_id=body.userId or "anonymous",
        idea_text=body.ideaText,
        status=PipelineStatus.RUNNING,
        agents_state={},
    )
    db.add(pipeline)
    await db.commit()

    # Launch pipeline as asyncio task (avoids BackgroundTasks session conflicts)
    asyncio.create_task(start_pipeline(body.ideaText, pipeline_id))

    return StartPipelineResponse(
        pipelineId=pipeline_id,
        status="running",
        message="Pipeline started. Connect to SSE stream for real-time updates.",
    )


@router.get("/{pipeline_id}/status")
async def get_status(pipeline_id: str, db: AsyncSession = Depends(get_db)):
    """Return current pipeline state — checks in-memory first, then DB."""
    # Fast path: in-memory state for active pipelines
    if pipeline_id in PIPELINE_MEMORY:
        return PIPELINE_MEMORY[pipeline_id]
    # Fall back to DB
    result = await db.execute(select(Pipeline).where(Pipeline.id == pipeline_id))
    pipeline = result.scalar_one_or_none()
    if not pipeline:
        raise HTTPException(status_code=404, detail="Pipeline not found")
    return pipeline.to_dict()


@router.get("/{pipeline_id}/stream")
async def stream(pipeline_id: str, db: AsyncSession = Depends(get_db)):
    """SSE endpoint — streams real-time agent status events."""
    # Accept if in-memory or in DB
    in_memory = pipeline_id in PIPELINE_MEMORY
    if not in_memory:
        result = await db.execute(select(Pipeline).where(Pipeline.id == pipeline_id))
        if not result.scalar_one_or_none():
            raise HTTPException(status_code=404, detail="Pipeline not found")

    return StreamingResponse(
        sse_service.event_stream(pipeline_id),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no", "Connection": "keep-alive"},
    )


@router.get("/{pipeline_id}/download")
async def download_zip(pipeline_id: str, db: AsyncSession = Depends(get_db)):
    """Generate and stream a ZIP of all agent outputs."""
    # Fetch state
    state = PIPELINE_MEMORY.get(pipeline_id)
    if not state:
        result = await db.execute(select(Pipeline).where(Pipeline.id == pipeline_id))
        p = result.scalar_one_or_none()
        if not p:
            raise HTTPException(status_code=404, detail="Pipeline not found")
        state = p.to_dict()

    agents = state.get("agents", {})
    buf = io.BytesIO()

    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # README
        idea = state.get("ideaText", "Your Startup Idea")
        zf.writestr("README.md", f"# LaunchForge AI — Startup Package\n\n**Idea:** {idea}\n\n"
                    "## Contents\n- `validation_report.json` — Market validation + opportunity score\n"
                    "- `strategy.json` — GTM + monetization plan\n"
                    "- `architecture.json` — Tech stack + system design\n"
                    "- `mvp_code/` — Generated MVP codebase\n"
                    "- `security_report.json` — OWASP Top 10 audit\n"
                    "- `marketing_kit.json` — Landing page copy + pitch deck\n"
                    "- `seo_strategy.json` — Keywords + content strategy\n\n"
                    "Generated by [LaunchForge AI](https://tb314nms.run.complete.dev)\n")

        # Agent outputs
        file_map = {
            "idea_validator": "validation_report.json",
            "strategy_planner": "strategy.json",
            "product_architect": "architecture.json",
            "security_reviewer": "security_report.json",
            "copywriter": "marketing_kit.json",
            "seo_optimizer": "seo_strategy.json",
        }
        for agent_id, filename in file_map.items():
            ag = agents.get(agent_id, {})
            result_data = ag.get("result", {})
            zf.writestr(filename, json.dumps(result_data, indent=2))

        # MVP code files
        code = agents.get("code_generator", {}).get("result", {})
        files = code.get("files", [])
        if isinstance(files, list):
            for f in files:
                if isinstance(f, dict) and f.get("path") and f.get("content"):
                    zf.writestr(f"mvp_code/{f['path']}", str(f["content"]))
        # .env.example
        env_vars = code.get("envVariables", [])
        if env_vars:
            zf.writestr("mvp_code/.env.example",
                        "\n".join(str(v) for v in env_vars) + "\n")

    buf.seek(0)
    slug = idea[:30].replace(" ", "-").lower()
    filename = f"launchforge-{slug}.zip"
    return StreamingResponse(
        iter([buf.getvalue()]),
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/list/{user_id}")
async def list_pipelines(user_id: str, db: AsyncSession = Depends(get_db)):
    result = await db.execute(
        select(Pipeline).where(Pipeline.user_id == user_id).order_by(Pipeline.created_at.desc())
    )
    return [p.to_dict() for p in result.scalars().all()]
